[[actions]]
name = "play"
platform = "windows"
path = "MossMod/MossMod.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "MossMod/MossMod"
args = ["--launched-through-itch"]
